name: Disabled - n8n CI/CD (manual only)

on:
  workflow_dispatch:

jobs:
  noop:
    runs-on: ubuntu-latest
    steps:
      - name: CI/CD disabled
        run: echo "CI/CD is disabled. Use scripts/deploy.sh or scripts/import_workflows.sh instead."

